name: Spring MVC
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "skandasbhat" --password-stdin
        docker image build -t skandasbhat/spring-mvc:latest .
        docker push skandasbhat/spring-mvc:latest      
    - name: run Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "skandasbhat" --password-stdin
        docker pull skandasbhat/spring-mvc:latest
        docker run skandasbhat/spring-mvc:latest
